type: object
x-stoplight:
  id: 051xnrd8lmbf8
description: 'Application id and name registered within the SE Asset Management system. If the application is both an API consumer and a proxy provider, it shares one of these records.'
required:
  - assetId
  - assetName
properties:
  assetId:
    type: string
    x-stoplight:
      id: x18py8ao5ql36
    description: Unique asset id for this application
    example: '50600'
  assetName:
    type: string
    x-stoplight:
      id: zge7wv1olwls1
    description: Application asset name
    example: SE API Management
title: Application Asset
