type: object
x-stoplight:
  id: 65ui3an4habhw
title: Environment Provider
description: |-
  An API provider application for a specific environment.

  A provider is also known as a backend application, a system that hosts the API service, lying behind the SEAPIM platform.
required:
  - assetId
  - createdAt
  - updatedAt
  - environment
properties:
  assetId:
    type: string
    x-stoplight:
      id: lzeo743ke0pp5
    example: '12345'
    description: 'Application asset id, as defined in the SE asset management system'
  providerUrls:
    type: array
    x-stoplight:
      id: 9u4nw6hbrdlk2
    description: Provider system URL for this API
    items:
      x-stoplight:
        id: 8bz6hv44szzhs
      type: string
      format: uri
  reverseProxies:
    type: array
    x-stoplight:
      id: dns6tppmzrj78
    description: 'Regional reverse proxy details, if the provided is hosted in the SE private network'
    items:
      x-stoplight:
        id: 6sgunwjh48xjk
      type: string
  instructions:
    type: string
    x-stoplight:
      id: 26su09cqvwgqg
    description: Extra information to help connect with a provider
  createdAt:
    $ref: ../models/CreatedAt.yaml
    description: The time this record was created
    x-stoplight:
      id: hcd85hg1c9lsa
  updatedAt:
    $ref: ../models/UpdatedAt.yaml
    description: The time this record was last updated
    x-stoplight:
      id: bp6enwluh6l89
  environment:
    $ref: ./Environment.yaml
    x-stoplight:
      id: ryb746o645roa
    description: API requirements-related SEAPIM environment
